title: Kremer Christmas
author: Theo Kremer
email: ttkremer@gmail.com
description: >-
  Merry Christmas Mom, Dad, and Izzy!

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
